### ISSUE TITLE
archivematica-workflow service not started

### ISSUE THREAD

**Issue by Hwesta** [artefactual-labs/ansible-archivematica-workflow#2]
https://github.com/artefactual-labs/ansible-archivematica-workflow/blob/master/tasks/install.yml#L52-L55 enables the archivematica-workflow service so it will start on boot, but doesn't actually start it.  This should probably be

```yaml
- name: "Enable service"
  service:
    name: "archivematica-workflow"
    enabled: "yes"
    state: "started"
```
